name: ongtrieuhau861ip13pm030

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Select the rclone command to run"
        required: true
        default: "about"
        type: choice
        options:
          - "about"
          - "bisync"
          - "copy"
          - "copyto"
          - "copyurl"
          - "delete"
          - "deletefile"
          - "hashsum"
          - "link"
          - "listremotes"
          - "ls"
          - "lsd"
          - "lsf"
          - "lsjson"
          - "lsl"
          - "mkdir"
          - "mount"
          - "move"
          - "moveto"
          - "rmdir"
          - "rmdirs"
          - "selfupdate"
          - "size"
          - "sync"
          - "test"
          - "touch"
          - "tree"
          - "version"
      remotesource:
        description: "Select remote source"
        default: ""
        type: choice
        options:
          - ""
          - "bucket:"
          - "photo:upload"
          - "onedrive:"
          - "bucket03:"
          - "bucket04:"
      remotedest:
        description: "Select remote dest"
        default: ""
        type: choice
        options:
          - ""
          - "bucket:"
          - "photo:upload"
          - "onedrive:"
          - "bucket03:"
          - "bucket04:"
jobs:
  ongtrieuhau861ip13pm030:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize jobs
        run: |
          mkdir -p ./.artifact
          TZ='Asia/Bangkok' date +'%Y%m%d-%H%M' > date.txt
          echo "NOWDATE=$(cat date.txt)" >> $GITHUB_ENV
          echo "github.event.inputs.remotesource: ${{ github.event.inputs.remotesource }}"
          echo "github.event.inputs.remotedest: ${{ github.event.inputs.remotedest }}"

      - name: Check Initialize jobs
        run: |
          echo "The date variable is $NOWDATE"
          echo "env.NOWDATE is ${{ env.NOWDATE }}"

      - name: Install rclone offline
        run: |
          sudo cp ./bin/rclone /usr/bin/
          sudo chmod +x /usr/bin/rclone
          rclone version

      - name: Decode and configure rclone from secrets
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF_BASE64_01_ongtrieuhau861ip13pm030 }}" | base64 --decode > ~/.config/rclone/rclone.conf

      - name: Run ${{ github.event.inputs.command }}
        run: |
          argBuilder="${{ github.event.inputs.command }}"
          if [[ -n "${{ github.event.inputs.remotesource }}" ]]; then
            argBuilder="${argBuilder} ${{ github.event.inputs.remotesource }}"
            echo "$argBuilder"
          fi
          if [[ -n "${{ github.event.inputs.remotedest }}" ]]; then
            argBuilder="${argBuilder} ${{ github.event.inputs.remotedest }}"
            echo "$argBuilder"
          fi
          echo "[argBuilder] ==> $argBuilder"
          rclone $argBuilder --auto-confirm -v

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: rclonecloud-artifact-${{ env.NOWDATE }}-${{ github.run_id }}
          path: ./.artifact
          retention-days: 5
